<?php

# Modified for Modularization for Xoops 2 CMS
# Copyright (C) 2003  Michael van Dam - mvandam@caltech.edu

$modversion['name'] = _MI_MANTIS_NAME;
$modversion['version'] = '0.18.0a4';
$modversion['description'] = _MI_MANTIS_DESC;
$modversion['credits'] = 'The Mantis Project<br>Modularization by Michael van Dam';
$modversion['help'] = 'no help yet';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/mantis_slogo.png';
$modversion['dirname'] = 'mantis';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/xoops_db_generate.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'mantis_bug_file_table';
$modversion['tables'][1] = 'mantis_bug_history_table';
$modversion['tables'][2] = 'mantis_bug_monitor_table';
$modversion['tables'][3] = 'mantis_bug_relationship_table';
$modversion['tables'][4] = 'mantis_bug_table';
$modversion['tables'][5] = 'mantis_bug_text_table';
$modversion['tables'][6] = 'mantis_bugnote_table';
$modversion['tables'][7] = 'mantis_bugnote_text_table';
$modversion['tables'][8] = 'mantis_custom_field_project_table';
$modversion['tables'][9] = 'mantis_custom_field_string_table';
$modversion['tables'][10] = 'mantis_custom_field_table';
$modversion['tables'][11] = 'mantis_news_table';
$modversion['tables'][12] = 'mantis_project_category_table';
$modversion['tables'][13] = 'mantis_project_file_table';
$modversion['tables'][14] = 'mantis_project_table';
$modversion['tables'][15] = 'mantis_project_user_list_table';
$modversion['tables'][16] = 'mantis_project_version_table';
$modversion['tables'][17] = 'mantis_upgrade_table';
$modversion['tables'][18] = 'mantis_user_pref_table';
$modversion['tables'][19] = 'mantis_user_print_pref_table';
$modversion['tables'][20] = 'mantis_user_profile_table';
$modversion['tables'][21] = 'mantis_user_table';

// Admin things
$modversion['hasAdmin'] = 1;

// Blocks

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_MANTIS_SMNAME1;
$modversion['sub'][1]['url'] = 'view_all_bug_page.php';
$modversion['sub'][2]['name'] = _MI_MANTIS_SMNAME2;
$modversion['sub'][2]['url'] = 'bug_report_page.php';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'mantis_search';

// Comments
//$modversion['hasComments'] = 1;
//$modversion['comments']['itemName'] = 'lid';
//$modversion['comments']['pageName'] = 'singlelink.php';
//$modversion['comments']['extraParams'] = array('cid');
// Comment callback functions
//$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
//$modversion['comments']['callback']['approve'] = 'mylinks_com_approve';
//$modversion['comments']['callback']['update'] = 'mylinks_com_update';

// Config

$modversion['config'][1]['name'] = 'integrate_display';
$modversion['config'][1]['title'] = '_MI_MANTIS_INTEGRATEDISPLAY';
$modversion['config'][1]['description'] = '_MI_MANTIS_INETGRATEDISPLAYDSC';
$modversion['config'][1]['formtype'] = 'yesno';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 1;
